In [1]:
import processing.acled_events_processing as acled
import processing.rainfall_processing as rain
import processing.food_prices_processing as food
import pandas as pd
from utils.dates import train_start_date, end_date

In [2]:
download = False
remove_abyei = True
k = 0.5
event_col = "event_type"

In [3]:
processed_acled_df, acled_predictor_cols, raw_acled_df = acled.get_clean_data(
        download, remove_abyei, k, event_col
    )
combined_df = processed_acled_df
predictor_cols = acled_predictor_cols

all_regions  = combined_df["region"].unique()
all_months = pd.period_range(train_start_date, end_date, freq="M")

INFO:Events processing:Data grouped by event_type
INFO:Events processing:Escalation target set at 0.5 standard deviations above the mean.

In [4]:
print(len(all_regions))
print(len(all_months))

18
84

In [5]:
processed_rain_df, rain_predictor_cols = rain.get_clean_data(
                download=download,
                remove_abyei=remove_abyei,
                all_regions=all_regions,
                all_months=all_months)

INFO:hdx.api.configuration:No HDX base configuration parameter. Using default base configuration file: C:\Users\evely\PycharmProjects\msc-final-project\.venv\Lib\site-packages\hdx\api\hdx_base_configuration.yaml.
INFO:hdx.api.configuration:Loading HDX base configuration from: C:\Users\evely\PycharmProjects\msc-final-project\.venv\Lib\site-packages\hdx\api\hdx_base_configuration.yaml
INFO:hdx.api.configuration:No HDX configuration parameter and no configuration file at default path: C:\Users\evely\.hdx_configuration.yaml.
INFO:hdx.api.configuration:Read only access to HDX: True
INFO:Train model:download=False: Reading local file ../data/hdx\sdn-rainfall-subnat-full.csv

In [6]:
rain_regions  = processed_rain_df["region"].unique()
rain_months = pd.period_range(processed_rain_df["year_month"].min(), processed_rain_df["year_month"].max(), freq="M")

In [7]:
print(len(rain_regions))
print(len(rain_months))

18
84

In [8]:
processed_rain_df, rain_predictor_cols = rain.get_clean_data(
                download=download,
                remove_abyei=remove_abyei,
                all_regions=None,
                all_months=None)

INFO:Train model:download=False: Reading local file ../data/hdx\sdn-rainfall-subnat-full.csv

In [9]:
rain_regions  = processed_rain_df["region"].unique()
rain_months = pd.period_range(processed_rain_df["year_month"].min(), processed_rain_df["year_month"].max(), freq="M")

In [10]:
print(len(rain_regions))
print(len(rain_months))

18
84

In [11]:
processed_food_df, food_predictor_cols = food.get_clean_data(
                download=download,
                remove_abyei=remove_abyei,
                all_regions=all_regions,
                all_months=all_months
            )
food_regions  = processed_food_df["region"].unique()
food_months = pd.period_range(processed_food_df["year_month"].min(), processed_food_df["year_month"].max(), freq="M")

INFO:Train model:download=False: Reading local file ../data/hdx\Sudan - Food Prices.csv

In [12]:
print(len(food_regions))
print(len(food_months))

18
84

In [13]:
processed_food_df, food_predictor_cols = food.get_clean_data(
                download=download,
                remove_abyei=remove_abyei,
                all_regions=None,
                all_months=None
            )
food_regions  = processed_food_df["region"].unique()
food_months = pd.period_range(processed_food_df["year_month"].min(), processed_food_df["year_month"].max(), freq="M")

INFO:Train model:download=False: Reading local file ../data/hdx\Sudan - Food Prices.csv

In [14]:
print(len(food_regions))
print(len(food_months))

18
84

In [15]:
processed_rain_df

          region year_month  rainfall_3m_anomaly
1     Al Jazirah    2018-01            93.058950
2     Al Jazirah    2018-02            99.848770
3     Al Jazirah    2018-03           100.000000
4     Al Jazirah    2018-04           100.000000
5     Al Jazirah    2018-05            99.319920
...          ...        ...                  ...
1525  White Nile    2024-08           119.630200
1526  White Nile    2024-09           116.999080
1527  White Nile    2024-10           111.128426
1528  White Nile    2024-11           107.648660
1529  White Nile    2024-12           104.396126

[1512 rows x 3 columns]

In [16]:
processed_food_df

          region year_month  price_millet  price_sorghum  price_wheat_flour
1     Al Jazirah    2018-01           NaN            NaN                NaN
2     Al Jazirah    2018-02           NaN            NaN                NaN
3     Al Jazirah    2018-03           NaN            NaN                NaN
4     Al Jazirah    2018-04           NaN            NaN                NaN
5     Al Jazirah    2018-05           NaN            NaN                NaN
...          ...        ...           ...            ...                ...
1525  White Nile    2024-08      2.922857       2.086667               5.01
1526  White Nile    2024-09      3.460000       2.750000               5.85
1527  White Nile    2024-10      4.771429       2.783333               6.68
1528  White Nile    2024-11      3.131429       2.680000               5.84
1529  White Nile    2024-12      3.400000       2.226667               3.01

[1512 rows x 5 columns]