# Notebook for running the winning model

In [1]:
import json
from pathlib import Path

import pandas as pd

import processing.acled_events_processing as acled
from models.train_models import train_evaluate_model
from utils.data_prep import get_clean_combined_data

REPORTS_DIR = Path("evaluation/model_reports")
reports_dir = Path(REPORTS_DIR)
reports_dir.mkdir(parents=True, exist_ok=True)

In [2]:
def summarise(label, subset):
    n_true_pos = subset["y_true"].sum()
    n_caught = subset[(subset["y_true"] == 1) & (subset["y_pred"] == 1)].shape[0]
    recall = n_caught / n_true_pos if n_true_pos else float("nan")
    n_pred_pos = subset["y_pred"].sum()
    precision = n_caught / n_pred_pos if n_pred_pos else float("nan")
    print(
        f"{label}: {len(subset)} rows, {n_true_pos} true escalations, "
        f"{n_caught} caught -> recall={recall:.3f}, precision={precision:.3f}"
    )
    return {
        "n_rows": len(subset),
        "n_true_pos": int(n_true_pos),
        "n_caught": n_caught,
        "recall": recall,
        "precision": precision,
    }

In [3]:
def run_model(config, params):
    data_sources = [
        src
        for src, include in zip(
            ["food", "rain", "text"],
            [
                config["include_food"],
                config["include_rain"],
                config["include_text"],
            ],
        )
        if include
    ]

    model_data, predictor_cols = get_clean_combined_data(
        data_sources=data_sources,
        k=config["k"],
        event_col=config["event_col"],
        conflict_only_embeddings=config["conflict_only"],
    )

    final_params = {
        **params,
        "k": config["k"],
        "event_col": config["event_col"],
        "n_splits": config["n_splits"],
        "use_pca": config["use_pca"],
    }

    results, best_params, shap_importance, onset_predictions = train_evaluate_model(
        model_data,
        predictor_cols,
        final_params,
        best_params=True,  # skip RandomizedSearchCV
        use_pca=config["use_pca"],
        compute_shap=True,
        shap_sample_size=2000,
        return_onset_predictions=True,
    )
    return results, best_params, shap_importance, onset_predictions

In [4]:
def model_report(label, config, params):
    """Runs a model and prints the full report, same as before, but also
    returns a flat dict of key metrics so multiple models can be compared
    in a table afterwards without re-typing numbers by hand.
    """
    results, best_params, shap_importance, onset_predictions = run_model(config, params)
    print("========MODEL REPORT========")
    print(f"---Model: {label}\n")
    print("---Results\n")
    print(results)
    print("---Best Params\n")
    print(best_params)
    print("---SHAP Importance\n")
    print(shap_importance)

    onset_predictions["year_month"] = onset_predictions["year_month"].astype(str)
    war_outbreak = "2023-04"
    print("Pre and post war:")
    pre_war = onset_predictions[onset_predictions["year_month"] < war_outbreak]
    post_war = onset_predictions[onset_predictions["year_month"] >= war_outbreak]

    pre_war_summary = summarise("Pre-war  (Jan-Mar 2023)", pre_war)
    post_war_summary = summarise("Post-war (Apr-Dec 2023)", post_war)

    key_regions = [
        "Khartoum",
        "North Darfur",
        "South Darfur",
        "West Darfur",
        "Central Darfur",
        "East Darfur",
        "West Kordofan",
        "South Kordofan",
    ]

    print("-----Key war-affected regions\n")
    key_region_rows = onset_predictions[onset_predictions["region"].isin(key_regions)]
    key_regions_summary = summarise("Key regions (all onset months)", key_region_rows)

    khartoum_rows = onset_predictions[onset_predictions["region"] == "Khartoum"]
    khartoum_summary = summarise("  Khartoum", khartoum_rows)

    for region in key_regions:
        if region == "Khartoum":
            continue
        region_rows = onset_predictions[onset_predictions["region"] == region]
        if region_rows["y_true"].sum() > 0:
            summarise(f"  {region}", region_rows)

    comparison_row = {
        "model": label,
        "onset_aupr": float(results["onset_aupr"]),
        "active_aupr": float(results["active_aupr"]),
        "pre_war_recall": pre_war_summary["recall"],
        "post_war_recall": post_war_summary["recall"],
        "khartoum_recall": khartoum_summary["recall"],
        "key_regions_recall": key_regions_summary["recall"],
    }

    return results, best_params, shap_importance, onset_predictions, comparison_row

In [5]:
def save_model_report(label, results, best_params, shap_importance, onset_predictions):
    label_formatted = label.replace(" ", "_").replace("(", "").replace(")","")
    
    with open(REPORTS_DIR / f"{label_formatted}_results.json", "w") as f:
        json.dump(results, f, indent=2)
    
    with open(REPORTS_DIR / f"{label_formatted}_best_params.json", "w") as f:
        json.dump(best_params, f, indent=2)
        
    shap_importance.to_csv(REPORTS_DIR / f"{label_formatted}_shap.csv", index=False)
    onset_predictions.to_csv(REPORTS_DIR / f"{label_formatted}_onset_predictions.csv", index=False)

In [6]:
def open_model_report(label):
    label_formatted = label.replace(" ", "_").replace("(", "").replace(")","")

    with open(REPORTS_DIR / f"{label_formatted}_results.json") as f:
            results = json.load(f)
    with open(REPORTS_DIR / f"{label_formatted}_best_params.json") as f:
        best_params = json.load(f)
    shap_importance = pd.read_csv(REPORTS_DIR / f"{label_formatted}_shap.csv")
    onset_predictions = pd.read_csv(REPORTS_DIR / f"{label_formatted}_onset_predictions.csv")
    
    return results, best_params, shap_importance, onset_predictions

## Model A - Structural only

In [18]:
model_a_config = {
    "include_food": True,
    "include_rain": True,
    "include_text": False,
    "conflict_only": None,
    "k": 1.75,
    "event_col": "sub_event_type",
    "n_splits": 5,
    "use_pca": False,
}

# (acled_sub_food_rain_threshold_change_1.75_5, onset_aupr=0.3336, active_aupr=0.2025)
model_a_xgb_params = {
    "max_depth": 3,
    "min_child_weight": 1,
    "max_delta_step": 0,
    "gamma": 0,
    "learning_rate": 0.01,
    "subsample": 0.6,
    "colsample_bytree": 0.8,
    "reg_alpha": 2.0,
    "reg_lambda": 1,
    "colsample_bylevel": 1.0,
}

In [19]:
results_a, best_params_a, shap_a, onset_preds_a, row_a = model_report(
    "Model A", model_a_config, model_a_xgb_params
)
save_model_report("Model A", results_a, best_params_a, shap_a, onset_preds_a)

INFO:AcledClient:Access token correctly retrieved.
INFO:AcledClient:Reading data from data/acled/acled_sudan.csv.
INFO:Events processing:Data grouped by sub_event_type
INFO:Events processing:Escalation target set at 1.75 standard deviations above the mean.
INFO:Data preparation:ACLED data processed.
INFO:HDXClient:Reading local file: data/hdx/hdx_sudan_food_prices.csv
INFO:Name Mapping:Renamed region 'Eastern Darfur' to 'East Darfur' (manual override)
INFO:Name Mapping:Renamed region 'Al Gezira' to 'Al Jazirah' (manual override)
INFO:Name Mapping:Renamed region 'Nile' to 'River Nile' (manual override)
INFO:Data preparation:Food prices data processed.
INFO:Name Mapping:Creating a PCODE map for rainfall data. This may take a few seconds...
INFO:HDXClient:Reading local file data/hdx/admin_boundaries/hdx_sdn_admin1.geojson
INFO:HDXClient:Reading local file: data/hdx/hdx_sdn_rainfall_subnat_full.csv
INFO:Name Mapping:Renamed region 'Aj Jazirah' to 'Al Jazirah' (manual override)
INFO:Rainfall Processing:Rainfall PCODEs mapped to regions.
INFO:Data preparation:Rainfall data processed.
INFO:Cross validation:Cross-validation testing splits:

--- Fold 1 ---
Train window: 2018-01 to 2018-10 (180 rows)
Test window:  2018-11 to 2019-08 (180 rows)
------------------------------
--- Fold 2 ---
Train window: 2018-01 to 2019-08 (360 rows)
Test window:  2019-09 to 2020-06 (180 rows)
------------------------------
--- Fold 3 ---
Train window: 2018-01 to 2020-06 (540 rows)
Test window:  2020-07 to 2021-04 (180 rows)
------------------------------
--- Fold 4 ---
Train window: 2018-01 to 2021-04 (720 rows)
Test window:  2021-05 to 2022-02 (180 rows)
------------------------------
--- Fold 5 ---
Train window: 2018-01 to 2022-02 (900 rows)
Test window:  2022-03 to 2022-12 (180 rows)
------------------------------
========MODEL REPORT========
---Model: Model A

---Results

{'optimal_threshold': '0.4255', 'n_predictors': 31, 'onset_aupr': '0.3336', 'onset_precision_class1': '0.2736', 'onset_recall_class1': '0.5918', 'onset_f1_class1': '0.3742', 'active_aupr': '0.2025', 'active_precision_class1': '0.1860', 'active_recall_class1': '0.5517', 'active_f1_class1': '0.2783'}
---Best Params

{'max_depth': 3, 'min_child_weight': 1, 'max_delta_step': 0, 'gamma': 0, 'learning_rate': 0.01, 'subsample': 0.6, 'colsample_bytree': 0.8, 'reg_alpha': 2.0, 'reg_lambda': 1, 'colsample_bylevel': 1.0, 'k': 1.75, 'event_col': 'sub_event_type', 'n_splits': 5, 'use_pca': False}
---SHAP Importance

                               feature  mean_abs_shap
0                      rolling_mean_6m       0.219327
1                       rolling_std_6m       0.098186
2                          armed_clash       0.051409
3                         price_millet       0.050923
4                  rainfall_3m_anomaly       0.049733
5                               attack       0.046501
6                        price_sorghum       0.039835
7                    price_wheat_flour       0.022563
8         looting_property_destruction       0.019962
9   excessive_force_against_protesters       0.015097
10                          fatalities       0.014777
11                    peaceful_protest       0.013766
12            change_to_group_activity       0.003401
13           protest_with_intervention       0.001990
14                        mob_violence       0.001183
15                     sexual_violence       0.000794
16                             arrests       0.000640
17   shelling_artillery_missile_attack       0.000275
18               violent_demonstration       0.000159
19        government_regains_territory       0.000157
20                               other       0.000118
21      abduction_forced_disappearance       0.000000
22       remote_explosive_landmine_ied       0.000000
23   non_violent_transfer_of_territory       0.000000
24                           agreement       0.000000
25    headquarters_or_base_established       0.000000
26                             grenade       0.000000
27               disrupted_weapons_use       0.000000
28                     chemical_weapon       0.000000
29                    air_drone_strike       0.000000
Pre and post war:
Pre-war  (Jan-Mar 2023): 54 rows, 8 true escalations, 5 caught -> recall=0.625, precision=0.172
Post-war (Apr-Dec 2023): 162 rows, 41 true escalations, 24 caught -> recall=0.585, precision=0.312
-----Key war-affected regions

Key regions (all onset months): 96 rows, 27 true escalations, 15 caught -> recall=0.556, precision=0.333
  Khartoum: 12 rows, 5 true escalations, 1 caught -> recall=0.200, precision=1.000
  North Darfur: 12 rows, 1 true escalations, 1 caught -> recall=1.000, precision=0.250
  South Darfur: 12 rows, 4 true escalations, 1 caught -> recall=0.250, precision=0.333
  West Darfur: 12 rows, 5 true escalations, 3 caught -> recall=0.600, precision=0.750
  Central Darfur: 12 rows, 3 true escalations, 1 caught -> recall=0.333, precision=0.167
  East Darfur: 12 rows, 3 true escalations, 3 caught -> recall=1.000, precision=0.250
  West Kordofan: 12 rows, 4 true escalations, 4 caught -> recall=1.000, precision=0.400
  South Kordofan: 12 rows, 2 true escalations, 1 caught -> recall=0.500, precision=0.200

## Model B

### Best model (conflict-only text)

In [ ]:
# --- Model B: numeric + food + rain + text (matched to Model A) ---
model_b_config = {
    "include_food": True,
    "include_rain": True,
    "include_text": True,
    "conflict_only": True,
    "k": 1.75,
    "event_col": "sub_event_type",
    "n_splits": 5,
    "use_pca": True,
}

# (acled_sub_food_rain_text_conflict_pca_1.75_5, onset_aupr=0.3941, active_aupr=0.2155)
model_b_xgb_params = {
    "max_depth": 7,
    "min_child_weight": 1,
    "max_delta_step": 0,
    "gamma": 3,
    "learning_rate": 0.01,
    "subsample": 1.0,
    "colsample_bytree": 1.0,
    "reg_alpha": 2.0,
    "reg_lambda": 10,
    "colsample_bylevel": 0.8,
}

In [10]:
(results_b_conflict,
    best_params_b_conflict,
    shap_b_conflict,
    onset_preds_b_conflict,
    row_b_conflict,
) = model_report("Model B (conflict-only text)", model_b_config, model_b_xgb_params)

save_model_report("Model B (conflict-only text)", results_b_conflict,
    best_params_b_conflict,
    shap_b_conflict,
    onset_preds_b_conflict,)

INFO:AcledClient:Access token correctly retrieved.
INFO:AcledClient:Reading data from data/acled/acled_sudan.csv.
INFO:Events processing:Data grouped by sub_event_type
INFO:Events processing:Escalation target set at 1.75 standard deviations above the mean.
INFO:Data preparation:ACLED data processed.
INFO:HDXClient:Reading local file: data/hdx/hdx_sudan_food_prices.csv
INFO:Name Mapping:Renamed region 'Eastern Darfur' to 'East Darfur' (manual override)
INFO:Name Mapping:Renamed region 'Al Gezira' to 'Al Jazirah' (manual override)
INFO:Name Mapping:Renamed region 'Nile' to 'River Nile' (manual override)
INFO:Data preparation:Food prices data processed.
INFO:Name Mapping:Creating a PCODE map for rainfall data. This may take a few seconds...
INFO:HDXClient:Reading local file data/hdx/admin_boundaries/hdx_sdn_admin1.geojson
INFO:HDXClient:Reading local file: data/hdx/hdx_sdn_rainfall_subnat_full.csv
INFO:Name Mapping:Renamed region 'Aj Jazirah' to 'Al Jazirah' (manual override)
INFO:Rainfall Processing:Rainfall PCODEs mapped to regions.
INFO:Data preparation:Rainfall data processed.
INFO:Text processing:Reading local file: data/acled/acled_sudan_monthly_regional_embeddings_conflict_only.pkl
INFO:Data preparation:Notes data processed.
INFO:Text processing:PCA fit on train embeddings only: 768 raw dims -> 24 components for 90% variance.
INFO:Cross validation:Cross-validation testing splits:

--- Fold 1 ---
Train window: 2018-01 to 2018-10 (180 rows)
Test window:  2018-11 to 2019-08 (180 rows)
------------------------------
--- Fold 2 ---
Train window: 2018-01 to 2019-08 (360 rows)
Test window:  2019-09 to 2020-06 (180 rows)
------------------------------
--- Fold 3 ---
Train window: 2018-01 to 2020-06 (540 rows)
Test window:  2020-07 to 2021-04 (180 rows)
------------------------------
--- Fold 4 ---
Train window: 2018-01 to 2021-04 (720 rows)
Test window:  2021-05 to 2022-02 (180 rows)
------------------------------
--- Fold 5 ---
Train window: 2018-01 to 2022-02 (900 rows)
Test window:  2022-03 to 2022-12 (180 rows)
------------------------------
========MODEL REPORT========
---Model: Model B (conflict-only text)

---Results

{'optimal_threshold': '0.4370', 'n_predictors': 56, 'onset_aupr': '0.3941', 'onset_precision_class1': '0.3158', 'onset_recall_class1': '0.3673', 'onset_f1_class1': '0.3396', 'active_aupr': '0.2155', 'active_precision_class1': '0.1746', 'active_recall_class1': '0.3793', 'active_f1_class1': '0.2391'}
---Best Params

{'max_depth': 7, 'min_child_weight': 1, 'max_delta_step': 0, 'gamma': 3, 'learning_rate': 0.01, 'subsample': 1.0, 'colsample_bytree': 1.0, 'reg_alpha': 2.0, 'reg_lambda': 10, 'colsample_bylevel': 0.8, 'k': 1.75, 'event_col': 'sub_event_type', 'n_splits': 5, 'use_pca': True}
---SHAP Importance

                               feature  mean_abs_shap
0                      rolling_mean_6m       0.287883
1                       rolling_std_6m       0.098583
2                  rainfall_3m_anomaly       0.075858
3                                  PC3       0.058929
4                                 PC13       0.052425
5                        price_sorghum       0.047923
6                         price_millet       0.043205
7                          armed_clash       0.040701
8                    price_wheat_flour       0.033313
9                                 PC20       0.026338
10                    peaceful_protest       0.025369
11                                PC11       0.024485
12                                PC18       0.022157
13  excessive_force_against_protesters       0.020069
14        looting_property_destruction       0.014954
15                                PC23       0.011312
16                                PC16       0.011256
17                                 PC7       0.010398
18                                PC21       0.010300
19                                 PC1       0.010225
20                                PC15       0.009983
21                                PC12       0.009878
22                                PC22       0.009523
23                                PC19       0.009250
24                                 PC5       0.008403
25                                PC10       0.008370
26                                 PC4       0.007421
27                                PC24       0.006487
28                              attack       0.005942
29                                 PC8       0.005808
Pre and post war:
Pre-war  (Jan-Mar 2023): 54 rows, 8 true escalations, 2 caught -> recall=0.250, precision=0.154
Post-war (Apr-Dec 2023): 162 rows, 41 true escalations, 16 caught -> recall=0.390, precision=0.364
-----Key war-affected regions

Key regions (all onset months): 96 rows, 27 true escalations, 7 caught -> recall=0.259, precision=0.259
  Khartoum: 12 rows, 5 true escalations, 0 caught -> recall=0.000, precision=nan
  North Darfur: 12 rows, 1 true escalations, 0 caught -> recall=0.000, precision=0.000
  South Darfur: 12 rows, 4 true escalations, 0 caught -> recall=0.000, precision=0.000
  West Darfur: 12 rows, 5 true escalations, 1 caught -> recall=0.200, precision=0.500
  Central Darfur: 12 rows, 3 true escalations, 1 caught -> recall=0.333, precision=0.333
  East Darfur: 12 rows, 3 true escalations, 2 caught -> recall=0.667, precision=0.222
  West Kordofan: 12 rows, 4 true escalations, 2 caught -> recall=0.500, precision=0.400
  South Kordofan: 12 rows, 2 true escalations, 1 caught -> recall=0.500, precision=0.333

### Comparison (all text)

In [22]:
# --- Model B: numeric + food + rain + text (matched to Model A) ---
model_b_all_config = {
    "include_food": True,
    "include_rain": True,
    "include_text": True,
    "conflict_only": False,
    "k": 1.75,
    "event_col": "event_type",  # Broad events work best for narrative context
    "n_splits": 5,
    "use_pca": False,           # Raw embeddings retain the most predictive signal
}

model_b_all_xgb_params = {
    "max_depth": 5,
    "min_child_weight": 1,
    "max_delta_step": 1,
    "gamma": 5,
    "learning_rate": 0.01,
    "subsample": 0.6,
    "colsample_bytree": 0.8,
    "reg_alpha": 1.0,
    "reg_lambda": 5,
    "colsample_bylevel": 1.0,
}

In [23]:
results_b_all, best_params_b_all, shap_b_all, onset_preds_b_all, row_b_all = (
    model_report("Model B (all-event text)", model_b_all_config, model_b_all_xgb_params)
)
save_model_report("Model B (all-event text)",results_b_all, best_params_b_all, shap_b_all, onset_preds_b_all)

INFO:AcledClient:Access token correctly retrieved.
INFO:AcledClient:Reading data from data/acled/acled_sudan.csv.
INFO:Events processing:Data grouped by event_type
INFO:Events processing:Escalation target set at 1.75 standard deviations above the mean.
INFO:Data preparation:ACLED data processed.
INFO:HDXClient:Reading local file: data/hdx/hdx_sudan_food_prices.csv
INFO:Name Mapping:Renamed region 'Eastern Darfur' to 'East Darfur' (manual override)
INFO:Name Mapping:Renamed region 'Al Gezira' to 'Al Jazirah' (manual override)
INFO:Name Mapping:Renamed region 'Nile' to 'River Nile' (manual override)
INFO:Data preparation:Food prices data processed.
INFO:Name Mapping:Creating a PCODE map for rainfall data. This may take a few seconds...
INFO:HDXClient:Reading local file data/hdx/admin_boundaries/hdx_sdn_admin1.geojson
INFO:HDXClient:Reading local file: data/hdx/hdx_sdn_rainfall_subnat_full.csv
INFO:Name Mapping:Renamed region 'Aj Jazirah' to 'Al Jazirah' (manual override)
INFO:Rainfall Processing:Rainfall PCODEs mapped to regions.
INFO:Data preparation:Rainfall data processed.
INFO:Text processing:Reading local file: data/acled/acled_sudan_monthly_regional_embeddings.pkl
INFO:Data preparation:Notes data processed.
INFO:Cross validation:Cross-validation testing splits:

--- Fold 1 ---
Train window: 2018-01 to 2018-10 (180 rows)
Test window:  2018-11 to 2019-08 (180 rows)
------------------------------
--- Fold 2 ---
Train window: 2018-01 to 2019-08 (360 rows)
Test window:  2019-09 to 2020-06 (180 rows)
------------------------------
--- Fold 3 ---
Train window: 2018-01 to 2020-06 (540 rows)
Test window:  2020-07 to 2021-04 (180 rows)
------------------------------
--- Fold 4 ---
Train window: 2018-01 to 2021-04 (720 rows)
Test window:  2021-05 to 2022-02 (180 rows)
------------------------------
--- Fold 5 ---
Train window: 2018-01 to 2022-02 (900 rows)
Test window:  2022-03 to 2022-12 (180 rows)
------------------------------
========MODEL REPORT========
---Model: Model B (all-event text)

---Results

{'optimal_threshold': '0.4151', 'n_predictors': 782, 'onset_aupr': '0.3624', 'onset_precision_class1': '0.3010', 'onset_recall_class1': '0.6327', 'onset_f1_class1': '0.4079', 'active_aupr': '0.1733', 'active_precision_class1': '0.1436', 'active_recall_class1': '0.4655', 'active_f1_class1': '0.2195'}
---Best Params

{'max_depth': 5, 'min_child_weight': 1, 'max_delta_step': 1, 'gamma': 5, 'learning_rate': 0.01, 'subsample': 0.6, 'colsample_bytree': 0.8, 'reg_alpha': 1.0, 'reg_lambda': 5, 'colsample_bylevel': 1.0, 'k': 1.75, 'event_col': 'event_type', 'n_splits': 5, 'use_pca': False}
---SHAP Importance

                feature  mean_abs_shap
0       rolling_mean_6m       0.188282
1        rolling_std_6m       0.052377
2               emb_709       0.017605
3               emb_306       0.014611
4               emb_655       0.014593
5               emb_122       0.013329
6                emb_36       0.012974
7               emb_596       0.011891
8               emb_657       0.011594
9               emb_289       0.011284
10              emb_584       0.010690
11  rainfall_3m_anomaly       0.010165
12              emb_740       0.009636
13              emb_690       0.009604
14              emb_109       0.008665
15              emb_544       0.008494
16              emb_311       0.008200
17              emb_548       0.007875
18              emb_263       0.007423
19              emb_370       0.007213
20              emb_255       0.007133
21              emb_679       0.007063
22              emb_355       0.007004
23              emb_555       0.006958
24         price_millet       0.006892
25              emb_437       0.006712
26              emb_746       0.006599
27              emb_331       0.006516
28              emb_541       0.006400
29               emb_84       0.006396
Pre and post war:
Pre-war  (Jan-Mar 2023): 54 rows, 8 true escalations, 3 caught -> recall=0.375, precision=0.214
Post-war (Apr-Dec 2023): 162 rows, 41 true escalations, 28 caught -> recall=0.683, precision=0.315
-----Key war-affected regions

Key regions (all onset months): 96 rows, 27 true escalations, 19 caught -> recall=0.704, precision=0.328
  Khartoum: 12 rows, 5 true escalations, 2 caught -> recall=0.400, precision=0.333
  North Darfur: 12 rows, 1 true escalations, 1 caught -> recall=1.000, precision=0.100
  South Darfur: 12 rows, 4 true escalations, 2 caught -> recall=0.500, precision=0.286
  West Darfur: 12 rows, 5 true escalations, 4 caught -> recall=0.800, precision=0.571
  Central Darfur: 12 rows, 3 true escalations, 2 caught -> recall=0.667, precision=0.500
  East Darfur: 12 rows, 3 true escalations, 3 caught -> recall=1.000, precision=0.300
  West Kordofan: 12 rows, 4 true escalations, 4 caught -> recall=1.000, precision=0.500
  South Kordofan: 12 rows, 2 true escalations, 1 caught -> recall=0.500, precision=0.167

In [25]:
corpus_comparison = pd.DataFrame([row_a, row_b_conflict, row_b_all]).set_index("model")
corpus_comparison.loc["Difference (all-text - conflict-only)"] = (
    corpus_comparison.loc["Model B (all-event text)"]
    - corpus_comparison.loc["Model B (conflict-only text)"]
)
corpus_comparison.round(3)

,onset_aupr,active_aupr,pre_war_recall,post_war_recall,khartoum_recall,key_regions_recall
model,,,,,,
Model A,0.334,0.202,0.625,0.585,0.2,0.556
Model B (conflict-only text),0.394,0.216,0.250,0.390,0.0,0.259
Model B (all-event text),0.362,0.173,0.375,0.683,0.4,0.704
Difference (all-text - conflict-only),-0.032,-0.042,0.125,0.293,0.4,0.444

In [14]:
_, _, raw_df = acled.get_clean_data(k=1.75, event_col="sub_event_type")

if not isinstance(raw_df["year_month"].dtype, pd.PeriodDtype):
    raw_df["year_month"] = pd.to_datetime(raw_df["year_month"]).dt.to_period("M")

pre_war = raw_df[
    (raw_df["year_month"] >= "2023-01") & (raw_df["year_month"] <= "2023-03")
]

key_regions = [
    "Khartoum",
    "North Darfur",
    "South Darfur",
    "West Darfur",
    "Central Darfur",
    "East Darfur",
    "West Kordofan",
    "South Kordofan",
]

summary = (
    pre_war[pre_war["admin1"].isin(key_regions)]
    .groupby("admin1")
    .agg(total_events=("conflict", "size"), conflict_events=("conflict", "sum"))
)
summary["pct_conflict"] = (
    summary["conflict_events"] / summary["total_events"] * 100
).round(1)
summary.sort_values("conflict_events")

INFO:AcledClient:Access token correctly retrieved.
INFO:AcledClient:Reading data from data/acled/acled_sudan.csv.
INFO:Events processing:Data grouped by sub_event_type
INFO:Events processing:Escalation target set at 1.75 standard deviations above the mean.

                total_events  conflict_events  pct_conflict
admin1
East Darfur               10                4          40.0
West Kordofan             15                4          26.7
South Kordofan            30               15          50.0
West Darfur               32               22          68.8
Khartoum                 220               25          11.4
South Darfur              51               27          52.9
Central Darfur            38               29          76.3
North Darfur              85               44          51.8

In [15]:
import pandas as pd

from utils.constants import ACTIVE_END_DATE, ACTIVE_START_DATE

active_prevalence_records = []
for k_test in [1.75]:
    model_data, predictor_cols = get_clean_combined_data(
        data_sources=[],
        k=k_test,
        event_col="sub_event_type",
        conflict_only_embeddings=True,
    )
    active_slice = model_data[
        (model_data["year_month"] >= pd.Period(ACTIVE_START_DATE, freq="M"))
        & (model_data["year_month"] <= pd.Period(ACTIVE_END_DATE, freq="M"))
    ]
    n_total = len(active_slice)
    n_escalations = int(active_slice["target_escalation"].sum())
    active_prevalence_records.append(
        {
            "k": k_test,
            "active_prevalence_percentage": round(n_escalations / n_total * 100, 1),
            "n_escalations": n_escalations,
            "n_active_rows": n_total,
        }
    )

active_prevalence_df = pd.DataFrame(active_prevalence_records).set_index("k")
print(active_prevalence_df)

INFO:AcledClient:Access token correctly retrieved.
INFO:AcledClient:Reading data from data/acled/acled_sudan.csv.
INFO:Events processing:Data grouped by sub_event_type
INFO:Events processing:Escalation target set at 1.75 standard deviations above the mean.
INFO:Data preparation:ACLED data processed.

      active_prevalence_percentage  n_escalations  n_active_rows
k
1.75                          13.4             58            432

### AUPR relative to baseline

Raw AUPR values at k=1.75 are lower than at k=1.0 (Model A onset: 0.3379 vs 0.3213 previously;
active: 0.2242 vs 0.3693 previously), which could look like a regression. However, AUPR's
no-skill baseline equals the positive-class prevalence, which is itself lower at the stricter
k=1.75 threshold (22.7% onset, 16.2% active, vs 30.6% onset at k=1.0). Expressed as a lift over
that baseline, Model A achieves 1.49x on onset and 1.38x on active, a genuine, meaningful
improvement over chance, and the onset lift is comparable to or better than what was observed at
k=1.0. The apparent decline in raw AUPR is therefore largely explained by evaluating against a
stricter, more legitimate target, not by weaker model performance. [Model B's equivalent lift
figures are not yet available and require re-running with local embeddings access.]

### Regional performance

Onset-window recall varies substantially by region. Of the key regions in the onset months (Jan-Mar 2023), Model A caught 15 of the 27 true escalations. Notably, Model A only caught only 1 of 5 true escalations in Khartoum (recall 0.200) - the capital and the site of the actual April 2023 outbreak. Recall was better in East Darfur, catching 3 of 3 true esclations, and West Kordofan (4 of 4). 

Model B (which includes conflict-only text) has very poor regional performance, catching 0 esclations in Khatoum and only 7 of the 27 true escalations caught. 

The interesting thing is that at the regional level during the onset period, Model B with all text performs better in terms of recall. It manages to catch 23 of the 27 true escalations. Looking at the data for Khatoum this is likely because of the 220 events in the onset months, only 11.4% were conflict events, the others were things like strategic developments. 

These finding are of a very small sample size (1-5 true esclations per region) so can only be taken as tenative. Comparing Model B all text vs conflict-only text, all text